### ISSUE TITLE
Is it possible to use python plugin to modify the data stream?

### ISSUE THREAD

**Issue by timsainb** [fpbattaglia/PythonPlugin#32]
e.g. from the docs, bufferfunction takes in voltage data and returns events. Is it possible to do the same, but take in n_arr, and return n_arr voltage data? e.g. to implement your own bandpass filter, rather than use the built in one. Or would cython be too slow?

**Comment by Claybarn** [comment]
I believe Cython should be quick enough. Any modification to n_arr should alter the data that is passed along in the signal chain, since the pluginFunction (line 101 in plugin.pyx)  is given a pointer to the data buffer and np.asarray doesn't copy its argument if it is already the correct data type. So barring Cython doing anything weird, it should work, but don't trust it until you try it!

**Comment by timsainb** [comment]
Awesome, I'll try this, thanks!
